### ISSUE TITLE
Jenkins failing with no emulator

### ISSUE THREAD

**Issue by renegens** [renegens/Stray-Animals#2]

**Comment by renegens** [comment]
> com.android.builder.testing.api.DeviceException: No connected devices!

**Comment by digiou** [comment]
http://stackoverflow.com/questions/31264136/travis-ci-android-tests-no-connected-devices

I guess something like this?

**Comment by renegens** [comment]
Yes it worked with the travis.yml many thanks.

sudo: false
language: android
jdk: oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - node_modules
    - $HOME/.gradle/caches/

android:
  components:
    - platform-tools
    - tools
    
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-23

  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8


# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - echo $ADB_INSTALL_TIMEOUT
  - android list target
